autofetch_sources: True

networks:
  default: mainnet-fork


dependencies:
    - OpenZeppelin/openzeppelin-contracts@5.0.1
    - smartcontractkit/chainlink@1.11.0

compiler:
    solc:
        remappings:
          - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@5.0.1"
          - "@chainlink=smartcontractkit/chainlink@1.11.0"
